[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "picotool load --update --verify --execute -t elf"
linker = "flip-link"

[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "debug"

